[package]
name = "sam_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}  # Enables (de)serialization of structs into various formats
serde_json = "1.0.140"  # Implements (de)serialization of structs to/from JSON